
github:
  slug: 'IgorShkidchenko/rg_library'
  access_token: eda67f3f87e5f4870fe9444cad9cddf35ed88fce
  api_endpoint: https://api.github.com/
  web_endpoint: https://github.com/
max_warnings: 150
verbose: true

