# frozen_string_literal: true

require 'faker'
require 'yaml'
require_relative '../controllers/validator/errors'
require_relative '../controllers/validator/validator'
require_relative '../entities/book'
require_relative '../entities/author'
require_relative '../entities/order'
require_relative '../entities/reader'
require_relative '../controllers/library/statistics'
require_relative '../controllers/library/nice_vision'
require_relative '../controllers/data_base/uploader'
require_relative '../entities/library'
require_relative '../data_base/fake_db'
require_relative 'colors.rb'
