---
- - !ruby/object:Book
    title: God father
    author: !ruby/object:Author
      name: Mario Puzo
      biography: Mario Puzo lifes
- - !ruby/object:Author
    name: Mario Puzo
    biography: Mario Puzo lifes
- - !ruby/object:Reader
    name: Sherlock
    email: holms@gmail.com
    city: London
    street: Baker Street
    house: 221B
- - !ruby/object:Order
    book: !ruby/object:Book
      title: God father
      author: !ruby/object:Author
        name: Mario Puzo
        biography: Mario Puzo lifes
    reader: !ruby/object:Reader
      name: Sherlock
      email: holms@gmail.com
      city: London
      street: Baker Street
      house: 221B
    date: 2018-10-30 01:49:12.797493765 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: God father
      author: !ruby/object:Author
        name: Mario Puzo2
        biography: Mario Puzo lifes2
    reader: !ruby/object:Reader
      name: Sherlock
      email: holms@gmail.com
      city: London
      street: Baker Street
      house: 221B
    date: 2018-10-30 01:49:12.797518989 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Second Popular
      author: !ruby/object:Author
        name: Mario Puzo3
        biography: Mario Puzo lifes3
    reader: !ruby/object:Reader
      name: John
      email: holms@gmail.com
      city: London
      street: Baker Street
      house: 221B
    date: 2018-10-30 01:49:12.797526429 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Random book
      author: !ruby/object:Author
        name: Mario Puzo4
        biography: Mario Puzo lifes4
    reader: !ruby/object:Reader
      name: Sherlock
      email: holms@gmail.com
      city: London
      street: Baker Street
      house: 221B
    date: 2018-10-30 01:49:12.797533041 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: God father
      author: !ruby/object:Author
        name: Mario Puzo5
        biography: Mario Puzo lifes5
    reader: !ruby/object:Reader
      name: John
      email: holms@gmail.com
      city: London
      street: Baker Street
      house: 221B
    date: 2018-10-30 01:49:12.797540505 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Second Popular
      author: !ruby/object:Author
        name: Mario Puzo6
        biography: Mario Puzo lifes6
    reader: !ruby/object:Reader
      name: John
      email: holms@gmail.com
      city: London
      street: Baker Street
      house: 221B
    date: 2018-10-30 01:49:12.797547621 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Last Popular
      author: !ruby/object:Author
        name: Mario Puzo7
        biography: Mario Puzo lifes7
    reader: !ruby/object:Reader
      name: John
      email: holms@gmail.com
      city: London
      street: Baker Street
      house: 221B
    date: 2018-10-30 01:49:12.797554401 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: God father
      author: !ruby/object:Author
        name: Mario Puzo8
        biography: Mario Puzo lifes8
    reader: !ruby/object:Reader
      name: Smith
      email: holms@gmail.com
      city: London
      street: Baker Street
      house: 221B
    date: 2018-10-30 01:49:12.797561409 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: asd
      author: !ruby/object:Author
        name: Mario Puzo10
        biography: Mario Puzo lifes10
    reader: !ruby/object:Reader
      name: tester
      email: test@gmail.com
      city: test
      street: test Street
      house: 221B
    date: 2018-10-30 02:00:38.676920101 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: dda
      author: !ruby/object:Author
        name: Mario Puzo10
        biography: Mario Puzo lifes10
    reader: !ruby/object:Reader
      name: tester
      email: test@gmail.com
      city: test
      street: test Street
      house: 221B
    date: 2018-10-30 02:00:53.462300112 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: new
      author: !ruby/object:Author
        name: Mario Puzo10
        biography: Mario Puzo lifes10
    reader: !ruby/object:Reader
      name: tester
      email: test@gmail.com
      city: test
      street: test Street
      house: 221B
    date: 2018-10-30 02:01:38.769403788 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: test
      author: !ruby/object:Author
        name: Mario Puzo10
        biography: Mario Puzo lifes10
    reader: !ruby/object:Reader
      name: tester
      email: test@gmail.com
      city: test
      street: test Street
      house: 221B
    date: 2018-10-30 02:01:47.822927883 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: qwe
      author: !ruby/object:Author
        name: Mario Puzo10
        biography: Mario Puzo lifes10
    reader: !ruby/object:Reader
      name: tester
      email: test@gmail.com
      city: test
      street: test Street
      house: 221B
    date: 2018-10-30 02:02:00.483415011 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: d
      author: !ruby/object:Author
        name: Mario Puzo10
        biography: Mario Puzo lifes10
    reader: !ruby/object:Reader
      name: tester
      email: test@gmail.com
      city: test
      street: test Street
      house: 221B
    date: 2018-10-30 02:03:23.061965597 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: '1'
      author: !ruby/object:Author
        name: Mario Puzo10
        biography: Mario Puzo lifes10
    reader: !ruby/object:Reader
      name: tester
      email: test@gmail.com
      city: test
      street: test Street
      house: 221B
    date: 2018-10-30 02:03:52.219415534 +02:00
