---
- - !ruby/object:Book
    title: The Last Enemy
    author: &1 !ruby/object:Author
      name: Mrs. Judie Mitchell
      biography: " "
- - *1
  - !ruby/object:Author
    name: Bo Dach
    biography: " "
- - !ruby/object:Reader
    name: Orbert Caswell
    email: reedgislason@ebert.biz
    city: Bayasabhad
    street: Renner Loaf
    house: 6
- - !ruby/object:Order
    book: &4 !ruby/object:Book
      title: The Wings of the Dove
      author: !ruby/object:Author
        name: Alberta Schulist
        biography: " "
    reader: &3 !ruby/object:Reader
      name: Alester Florent
      email: cherishrenner@waelchi.com
      city: Volantis
      street: DuBuque Parks
      house: 10
    date: 2018-11-05 22:50:23.633391397 +02:00
  - !ruby/object:Order
    book: &2 !ruby/object:Book
      title: Consider the Lilies
      author: !ruby/object:Author
        name: Mariel Sawayn
        biography: " "
    reader: &5 !ruby/object:Reader
      name: Hullen
      email: fritzwolff@kautzer.net
      city: Ny Sar
      street: Hodkiewicz Ford
      house: 7
    date: 2018-11-05 22:50:23.633398945 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-05 22:50:23.633403397 +02:00
  - !ruby/object:Order
    book: *4
    reader: *5
    date: 2018-11-05 22:50:23.633407405 +02:00
  - !ruby/object:Order
    book: &6 !ruby/object:Book
      title: Françoise Sagan
      author: !ruby/object:Author
        name: Miss Gita Will
        biography: " "
    reader: !ruby/object:Reader
      name: Benfrey Frey
      email: avery@pollich.io
      city: Volantis
      street: Shanae Turnpike
      house: 4
    date: 2018-11-05 22:50:23.633412121 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: To a God Unknown
      author: !ruby/object:Author
        name: Donn Dickens
        biography: " "
    reader: *5
    date: 2018-11-05 22:50:23.633416633 +02:00
  - !ruby/object:Order
    book: *4
    reader: !ruby/object:Reader
      name: Kyle
      email: shantelle@damore.io
      city: Braavos
      street: Connie Streets
      house: 2
    date: 2018-11-05 22:50:23.633420641 +02:00
  - !ruby/object:Order
    book: *6
    reader: *3
    date: 2018-11-05 22:50:23.633505048 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-05 22:50:23.633509884 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-05 22:50:23.633514096 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-05 22:50:23.633518212 +02:00
