---
- - !ruby/object:Book
    title: The Stars' Tennis Balls
    author: &1 !ruby/object:Author
      name: Jeff Veum
      biography: ''
- - *1
- - !ruby/object:Reader
    name: Mirri Maz Duur
    email: jeffieschimmel@oreillyboyle.net
    city: Braavos
    street: Karlyn Rue
    house: 9
- - !ruby/object:Order
    book: &4 !ruby/object:Book
      title: Eyeless in Gaza
      author: !ruby/object:Author
        name: Keshia Lemke III
        biography: ''
    reader: &3 !ruby/object:Reader
      name: Lyonel
      email: junglegros@christiansenkovacek.biz
      city: Ar Noy
      street: Stracke Fields
      house: 5
    date: 2018-11-02 15:53:44.019452100 +02:00
  - !ruby/object:Order
    book: &2 !ruby/object:Book
      title: No Country for Old Men
      author: !ruby/object:Author
        name: Dee Bayer
        biography: ''
    reader: &5 !ruby/object:Reader
      name: Haggo
      email: darylfeest@mante.co
      city: Sunspear
      street: Wilderman Underpass
      house: 9
    date: 2018-11-02 15:53:44.019466740 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-02 15:53:44.019474504 +02:00
  - !ruby/object:Order
    book: *4
    reader: *5
    date: 2018-11-02 15:53:44.019480948 +02:00
  - !ruby/object:Order
    book: &6 !ruby/object:Book
      title: The Road Less Traveled
      author: !ruby/object:Author
        name: Samuel Harris
        biography: ''
    reader: !ruby/object:Reader
      name: Jyck
      email: darwin@cummingshackett.com
      city: Sar Meel
      street: Bins Spurs
      house: 9
    date: 2018-11-02 15:53:44.019487896 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: No Longer at Ease
      author: !ruby/object:Author
        name: Mrs. Amanda Herzog
        biography: ''
    reader: *5
    date: 2018-11-02 15:53:44.019494700 +02:00
  - !ruby/object:Order
    book: *4
    reader: !ruby/object:Reader
      name: Goodwin
      email: ellanienow@howeerdman.biz
      city: Old Ghis
      street: Muller Harbors
      house: 4
    date: 2018-11-02 15:53:44.019501492 +02:00
  - !ruby/object:Order
    book: *6
    reader: *3
    date: 2018-11-02 15:53:44.019507600 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-02 15:53:44.019513528 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-02 15:53:44.019519876 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-02 15:53:44.019525852 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Of Mice and Men
      author: !ruby/object:Author
        name: Sang Stehr
        biography: ''
    reader: !ruby/object:Reader
      name: Doran Martell
      email: marylouiseking@kilback.info
      city: Chroyane
      street: Denesik Vista
      house: 2
    date: 2018-11-02 15:53:44.036767435 +02:00
