---
- - !ruby/object:Book
    title: The Golden Apples of the Sun
    author: &1 !ruby/object:Author
      name: Reda Kiehn
      biography: 
- - *1
- - !ruby/object:Reader
    name: Rufus Leek
    email: belia@heathcotedurgan.org
    city: Tyria
    street: Goodwin Throughway
    house: 2
- - !ruby/object:Order
    book: &4 !ruby/object:Book
      title: Shall not Perish
      author: !ruby/object:Author
        name: Audria Crooks DVM
        biography: 
    reader: &3 !ruby/object:Reader
      name: Lotho Lornel
      email: bret@hoppe.io
      city: Yunkai
      street: Torphy Shore
      house: 6
    date: 2018-11-01 13:56:18.874513446 +02:00
  - !ruby/object:Order
    book: &2 !ruby/object:Book
      title: The Other Side of Silence
      author: !ruby/object:Author
        name: Anderson Carroll DVM
        biography: 
    reader: &5 !ruby/object:Reader
      name: Allyria Dayne
      email: keven@weimann.info
      city: Chroyane
      street: Reichert Mills
      house: 10
    date: 2018-11-01 13:56:18.874522877 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-01 13:56:18.874527425 +02:00
  - !ruby/object:Order
    book: *4
    reader: *5
    date: 2018-11-01 13:56:18.874531109 +02:00
  - !ruby/object:Order
    book: &6 !ruby/object:Book
      title: The Heart Is Deceitful Above All Things
      author: !ruby/object:Author
        name: Pedro Ernser
        biography: 
    reader: !ruby/object:Reader
      name: Tybolt Crakehall
      email: ardelle@aufderhar.biz
      city: Old Ghis
      street: Larson Lake
      house: 3
    date: 2018-11-01 13:56:18.874535093 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: A Many-Splendoured Thing
      author: !ruby/object:Author
        name: Pearle Adams
        biography: 
    reader: *5
    date: 2018-11-01 13:56:18.874539149 +02:00
  - !ruby/object:Order
    book: *4
    reader: !ruby/object:Reader
      name: Rickard Tyrell
      email: trudischiller@green.biz
      city: White Harbor
      street: Johnna Glens
      house: 4
    date: 2018-11-01 13:56:18.874542641 +02:00
  - !ruby/object:Order
    book: *6
    reader: *3
    date: 2018-11-01 13:56:18.874546013 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-01 13:56:18.874549121 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-01 13:56:18.874552193 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-01 13:56:18.874555277 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: The Last Temptation
      author: !ruby/object:Author
        name: Miss Hiedi Spinka
        biography: 
    reader: !ruby/object:Reader
      name: Donyse
      email: hsiuwatsica@konopelski.net
      city: Lys
      street: Herzog Pine
      house: 3
    date: 2018-11-01 13:56:21.572367587 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Frequent Hearses
      author: !ruby/object:Author
        name: Mr. Theo Reynolds
        biography: 
    reader: !ruby/object:Reader
      name: Aegon Blackfyre
      email: virgiezieme@kulas.org
      city: Braavos
      street: Schmeler Parkways
      house: 5
    date: 2018-11-01 14:12:31.415705194 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Mother Night
      author: !ruby/object:Author
        name: Manuel Carter
        biography: 
    reader: !ruby/object:Reader
      name: Garlan Tyrell
      email: carl@kirlinboehm.info
      city: Ar Noy
      street: Edmond Tunnel
      house: 8
    date: 2018-11-01 14:16:47.948654596 +02:00
