---
- - !ruby/object:Book
    title: A Summer Bird-Cage
    author: &1 !ruby/object:Author
      name: Mr. Mauricio Wisoky
      biography: ''
- - *1
- - !ruby/object:Reader
    name: Penny
    email: tysonhegmann@nikolaushermann.com
    city: Sar Meel
    street: Kurt Lakes
    house: 1
- - !ruby/object:Order
    book: &4 !ruby/object:Book
      title: Specimen Days
      author: !ruby/object:Author
        name: Garret DuBuque
        biography: ''
    reader: &3 !ruby/object:Reader
      name: Titus Peake
      email: eugeneosinski@rempel.org
      city: Chroyane
      street: Joannie Neck
      house: 10
    date: 2018-11-02 16:47:45.549696466 +02:00
  - !ruby/object:Order
    book: &2 !ruby/object:Book
      title: Mr Standfast
      author: !ruby/object:Author
        name: Alfredo Grimes
        biography: ''
    reader: &5 !ruby/object:Reader
      name: Desmond
      email: althea@schowalter.com
      city: Oros
      street: Bruen Rue
      house: 8
    date: 2018-11-02 16:47:45.549711910 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-02 16:47:45.549719734 +02:00
  - !ruby/object:Order
    book: *4
    reader: *5
    date: 2018-11-02 16:47:45.549725794 +02:00
  - !ruby/object:Order
    book: &6 !ruby/object:Book
      title: The Way Through the Woods
      author: !ruby/object:Author
        name: Reynaldo Lockman IV
        biography: ''
    reader: !ruby/object:Reader
      name: Softfoot
      email: bevstreich@stracke.com
      city: Qohor
      street: Lorri Junctions
      house: 6
    date: 2018-11-02 16:47:45.549771813 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Eyeless in Gaza
      author: !ruby/object:Author
        name: Deb Cormier Jr.
        biography: ''
    reader: *5
    date: 2018-11-02 16:47:45.549804897 +02:00
  - !ruby/object:Order
    book: *4
    reader: !ruby/object:Reader
      name: Robin Moreland
      email: vernell@sauer.name
      city: Vaes Dothrak
      street: Tyson Creek
      house: 2
    date: 2018-11-02 16:47:45.549812145 +02:00
  - !ruby/object:Order
    book: *6
    reader: *3
    date: 2018-11-02 16:47:45.549818529 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-02 16:47:45.549824397 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-02 16:47:45.549830433 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-02 16:47:45.549836409 +02:00
