---
- - !ruby/object:Book
    title: To Say Nothing of the Dog
    author: &1 !ruby/object:Author
      name: Dr. Genie Abshire
      biography: ''
  - &8 !ruby/object:Book
    title: Stranger in a Strange Land
    author: &2 !ruby/object:Author
      name: Mckenzie Rippin
      biography: ''
- - *1
  - *2
- - !ruby/object:Reader
    name: Ironbelly
    email: annis@jast.com
    city: Yunkai
    street: Michale Meadow
    house: 9
  - &9 !ruby/object:Reader
    name: Wynafryd Manderly
    email: korysmith@cartwright.info
    city: Astapor
    street: Alissa Shores
    house: 4
- - !ruby/object:Order
    book: &5 !ruby/object:Book
      title: Blood's a Rover
      author: !ruby/object:Author
        name: Berta Tremblay
        biography: ''
    reader: &4 !ruby/object:Reader
      name: Canker Jeyne
      email: enriqueledner@quitzon.com
      city: Oldtown
      street: Koepp Manors
      house: 8
    date: 2018-11-11 22:34:20.791910883 +02:00
  - !ruby/object:Order
    book: &3 !ruby/object:Book
      title: Vile Bodies
      author: !ruby/object:Author
        name: Donnell Padberg
        biography: ''
    reader: &6 !ruby/object:Reader
      name: Ronel Rivers
      email: rico@feest.co
      city: Gulltown
      street: Hahn Passage
      house: 2
    date: 2018-11-11 22:34:20.791925487 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-11 22:34:20.791931199 +02:00
  - !ruby/object:Order
    book: *5
    reader: *6
    date: 2018-11-11 22:34:20.791935315 +02:00
  - !ruby/object:Order
    book: &7 !ruby/object:Book
      title: Mother Night
      author: !ruby/object:Author
        name: Rosaline Hilpert Jr.
        biography: ''
    reader: !ruby/object:Reader
      name: Mebble
      email: marcellondricka@hirthe.com
      city: Chroyane
      street: Mills Village
      house: 8
    date: 2018-11-11 22:34:20.791977267 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Consider the Lilies
      author: !ruby/object:Author
        name: Indira Purdy PhD
        biography: ''
    reader: *6
    date: 2018-11-11 22:34:20.791982703 +02:00
  - !ruby/object:Order
    book: *5
    reader: !ruby/object:Reader
      name: Dorea Sand
      email: jasper@hermanpadberg.net
      city: Old Ghis
      street: Watsica Ports
      house: 8
    date: 2018-11-11 22:34:20.791986819 +02:00
  - !ruby/object:Order
    book: *7
    reader: *4
    date: 2018-11-11 22:34:20.791990755 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-11 22:34:20.791994715 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-11 22:34:20.791998483 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-11 22:34:20.792002275 +02:00
  - !ruby/object:Order
    book: *8
    reader: *9
    date: 2018-11-11 22:34:20.808888051 +02:00
