---
- - !ruby/object:Book
    title: Beneath the Bleeding
    author: &1 !ruby/object:Author
      name: Stanton Bode DVM
      biography: ''
  - &8 !ruby/object:Book
    title: A Swiftly Tilting Planet
    author: &2 !ruby/object:Author
      name: Robbie Williamson
      biography: ''
- - *1
  - *2
- - !ruby/object:Reader
    name: Wyl Waynwood
    email: carrollwaelchi@heathcotekeebler.biz
    city: Elyria
    street: Heathcote Spring
    house: 9
  - &9 !ruby/object:Reader
    name: Gormon Peake
    email: irvingwiza@franecki.org
    city: Meereen
    street: Huels Crescent
    house: 8
- - !ruby/object:Order
    book: &5 !ruby/object:Book
      title: No Country for Old Men
      author: !ruby/object:Author
        name: Pedro Hilpert
        biography: ''
    reader: &4 !ruby/object:Reader
      name: Miklaz
      email: juliagislason@stoltenberg.org
      city: Braavos
      street: Roob Prairie
      house: 7
    date: 2018-11-04 15:42:42.112909377 +02:00
  - !ruby/object:Order
    book: &3 !ruby/object:Book
      title: For a Breath I Tarry
      author: !ruby/object:Author
        name: Chiquita Brown
        biography: ''
    reader: &6 !ruby/object:Reader
      name: Othor
      email: lashaunlesch@ullrich.com
      city: Tolos
      street: Renato Street
      house: 9
    date: 2018-11-04 15:42:42.112921641 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-04 15:42:42.112926729 +02:00
  - !ruby/object:Order
    book: *5
    reader: *6
    date: 2018-11-04 15:42:42.112930833 +02:00
  - !ruby/object:Order
    book: &7 !ruby/object:Book
      title: Consider Phlebas
      author: !ruby/object:Author
        name: Shelton Spencer
        biography: ''
    reader: !ruby/object:Reader
      name: Ronnet Connington
      email: jefferyfisher@kiehn.io
      city: Yunkai
      street: Morar Lock
      house: 9
    date: 2018-11-04 15:42:42.112935741 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Cover Her Face
      author: !ruby/object:Author
        name: Eric Osinski
        biography: ''
    reader: *6
    date: 2018-11-04 15:42:42.112940037 +02:00
  - !ruby/object:Order
    book: *5
    reader: !ruby/object:Reader
      name: Gilwood Hunter
      email: xeniadickens@hayes.net
      city: Oldtown
      street: Petronila Course
      house: 8
    date: 2018-11-04 15:42:42.112944033 +02:00
  - !ruby/object:Order
    book: *7
    reader: *4
    date: 2018-11-04 15:42:42.112947897 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-04 15:42:42.112951725 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-04 15:42:42.112955493 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-04 15:42:42.112959309 +02:00
  - !ruby/object:Order
    book: *8
    reader: *9
    date: 2018-11-04 15:42:42.130117807 +02:00
