---
- - !ruby/object:Book
    title: Noli Me Tangere
    author: &1 !ruby/object:Author
      name: Ms. Israel Bauch
      biography: ''
- - *1
  - !ruby/object:Author
    name: Simona Wehner
    biography: ''
- - !ruby/object:Reader
    name: Rhea Florent
    email: iradurgan@crist.com
    city: Sar Meel
    street: Donnelly Harbor
    house: 10
- - !ruby/object:Order
    book: &4 !ruby/object:Book
      title: I Sing the Body Electric
      author: !ruby/object:Author
        name: Nita Jenkins
        biography: ''
    reader: &3 !ruby/object:Reader
      name: Will
      email: palmerkoch@donnelly.info
      city: Astapor
      street: Lauren Run
      house: 9
    date: 2018-11-06 16:30:26.629157099 +02:00
  - !ruby/object:Order
    book: &2 !ruby/object:Book
      title: It's a Battlefield
      author: !ruby/object:Author
        name: Shaun Braun PhD
        biography: ''
    reader: &5 !ruby/object:Reader
      name: Steffarion Sparr
      email: leifcain@upton.co
      city: Pentos
      street: Carmina Stravenue
      house: 5
    date: 2018-11-06 16:30:26.629164874 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-06 16:30:26.629169494 +02:00
  - !ruby/object:Order
    book: *4
    reader: *5
    date: 2018-11-06 16:30:26.629173357 +02:00
  - !ruby/object:Order
    book: &6 !ruby/object:Book
      title: The Moving Toyshop
      author: !ruby/object:Author
        name: Karol Auer
        biography: ''
    reader: !ruby/object:Reader
      name: Selmond Stackspear
      email: delmar@bartellhowe.biz
      city: Lorath
      street: Gaylord Flats
      house: 2
    date: 2018-11-06 16:30:26.629177905 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: The Glory and the Dream
      author: !ruby/object:Author
        name: Spring Simonis
        biography: ''
    reader: *5
    date: 2018-11-06 16:30:26.629182008 +02:00
  - !ruby/object:Order
    book: *4
    reader: !ruby/object:Reader
      name: Sargon Botley
      email: lupe@senger.io
      city: Lys
      street: Wolff Ridges
      house: 10
    date: 2018-11-06 16:30:26.629185944 +02:00
  - !ruby/object:Order
    book: *6
    reader: *3
    date: 2018-11-06 16:30:26.629189687 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-06 16:30:26.629193731 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-06 16:30:26.629197679 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-06 16:30:26.629201566 +02:00
