---
- - !ruby/object:Book
    title: The Golden Bowl
    author: &1 !ruby/object:Author
      name: Antoine Kuhlman MD
      biography: 
- - *1
- - !ruby/object:Reader
    name: Joanna Swyft
    email: hue@johnsonlarkin.net
    city: Norvos
    street: Diego Crossroad
    house: 7
- - !ruby/object:Order
    book: &4 !ruby/object:Book
      title: From Here to Eternity
      author: !ruby/object:Author
        name: Cyndy McLaughlin
        biography: 
    reader: &3 !ruby/object:Reader
      name: Damon Lannister
      email: willia@weinataufderhar.io
      city: Sar Meel
      street: Luettgen Passage
      house: 1
    date: 2018-11-01 13:32:52.866177499 +02:00
  - !ruby/object:Order
    book: &2 !ruby/object:Book
      title: Jacob Have I Loved
      author: !ruby/object:Author
        name: Alina Kuhic
        biography: 
    reader: &5 !ruby/object:Reader
      name: Allar Deem
      email: miliatrantow@leannon.name
      city: Ar Noy
      street: Buford Islands
      house: 2
    date: 2018-11-01 13:32:52.866185803 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-01 13:32:52.866190063 +02:00
  - !ruby/object:Order
    book: *4
    reader: *5
    date: 2018-11-01 13:32:52.866193435 +02:00
  - !ruby/object:Order
    book: &6 !ruby/object:Book
      title: An Instant In The Wind
      author: !ruby/object:Author
        name: Terrence Goyette
        biography: 
    reader: !ruby/object:Reader
      name: Rakharo
      email: tommie@mckenzielegros.co
      city: Lys
      street: Cummings Ridges
      house: 8
    date: 2018-11-01 13:32:52.866197287 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Gone with the Wind
      author: !ruby/object:Author
        name: Wes Lehner
        biography: 
    reader: *5
    date: 2018-11-01 13:32:52.866200983 +02:00
  - !ruby/object:Order
    book: *4
    reader: !ruby/object:Reader
      name: Marillion
      email: fredricschulist@mannprice.biz
      city: Tyria
      street: Johns Summit
      house: 9
    date: 2018-11-01 13:32:52.866204307 +02:00
  - !ruby/object:Order
    book: *6
    reader: *3
    date: 2018-11-01 13:32:52.866207475 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-01 13:32:52.866210739 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-01 13:32:52.866213883 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-01 13:32:52.866216991 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: An Instant In The Wind
      author: !ruby/object:Author
        name: Stephan Jacobi
        biography: 
    reader: !ruby/object:Reader
      name: Joss the Gloom
      email: laurence@romaguera.name
      city: Tyrosh
      street: Shad Stream
      house: 7
    date: 2018-11-01 13:32:55.558192602 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: The Curious Incident of the Dog in the Night-Time
      author: !ruby/object:Author
        name: Rene Mosciski
        biography: 
    reader: !ruby/object:Reader
      name: Jason Lannister
      email: lakendralakin@lind.name
      city: Ny Sar
      street: Orn Centers
      house: 7
    date: 2018-11-01 13:34:24.981742668 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Infinite Jest
      author: !ruby/object:Author
        name: Ms. Irwin Wisoky
        biography: 
    reader: !ruby/object:Reader
      name: Vargo Hoat
      email: annicecollier@homenick.co
      city: Vaes Dothrak
      street: Lawerence Valley
      house: 8
    date: 2018-11-01 13:37:55.949282921 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Surprised by Joy
      author: !ruby/object:Author
        name: Sydney Nikolaus IV
        biography: 
    reader: !ruby/object:Reader
      name: Leana Frey
      email: bernardkuhn@bashirianhickle.name
      city: Lorath
      street: Bosco Summit
      house: 9
    date: 2018-11-01 13:39:08.177619083 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Unweaving the Rainbow
      author: !ruby/object:Author
        name: Ulysses Dickens
        biography: 
    reader: !ruby/object:Reader
      name: Rosamund Lannister
      email: lindsaykovacek@huel.name
      city: Qohor
      street: Meghann Camp
      house: 7
    date: 2018-11-01 13:39:17.378388012 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: A Passage to India
      author: !ruby/object:Author
        name: Elisha Macejkovic
        biography: 
    reader: !ruby/object:Reader
      name: Harsley
      email: halschoen@greenkonopelski.org
      city: Old Ghis
      street: Joshua Key
      house: 7
    date: 2018-11-01 13:42:03.080096851 +02:00
