---
- - !ruby/object:Book
    title: The Mermaids Singing
    author: &1 !ruby/object:Author
      name: Ms. Maxwell Leannon
      biography: ''
- - *1
- - !ruby/object:Reader
    name: Alyn Estermont
    email: setsuko@roobfeest.com
    city: Sar Meel
    street: Calista Trail
    house: 3
- - !ruby/object:Order
    book: &4 !ruby/object:Book
      title: Nine Coaches Waiting
      author: !ruby/object:Author
        name: Alexis Gislason MD
        biography: ''
    reader: &3 !ruby/object:Reader
      name: Hibald
      email: emmitt@bartell.info
      city: Tyria
      street: Jenkins Spurs
      house: 1
    date: 2018-11-09 01:30:28.026239425 +02:00
  - !ruby/object:Order
    book: &2 !ruby/object:Book
      title: Sleep the Brave
      author: !ruby/object:Author
        name: Lester Veum
        biography: ''
    reader: &5 !ruby/object:Reader
      name: Courtenay Greenhill
      email: xavier@binsledner.biz
      city: Qarth
      street: Lou Heights
      house: 10
    date: 2018-11-09 01:30:28.026251905 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-09 01:30:28.026257317 +02:00
  - !ruby/object:Order
    book: *4
    reader: *5
    date: 2018-11-09 01:30:28.026261673 +02:00
  - !ruby/object:Order
    book: &6 !ruby/object:Book
      title: Have His Carcase
      author: !ruby/object:Author
        name: Geneva Miller
        biography: ''
    reader: !ruby/object:Reader
      name: Yohn Farwynd
      email: marylouisewelch@mclaughlindietrich.biz
      city: Qohor
      street: Schiller Light
      house: 7
    date: 2018-11-09 01:30:28.026266413 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: The Yellow Meads of Asphodel
      author: !ruby/object:Author
        name: Ms. Orlando Rohan
        biography: ''
    reader: *5
    date: 2018-11-09 01:30:28.026270529 +02:00
  - !ruby/object:Order
    book: *4
    reader: !ruby/object:Reader
      name: Grigg
      email: delcie@willmsferry.co
      city: Myr
      street: Marcelino Station
      house: 8
    date: 2018-11-09 01:30:28.026274381 +02:00
  - !ruby/object:Order
    book: *6
    reader: *3
    date: 2018-11-09 01:30:28.026278185 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-09 01:30:28.026282109 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-09 01:30:28.026285889 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-09 01:30:28.026289717 +02:00
