---
- - !ruby/object:Book
    title: Recalled to Life
    author: &1 !ruby/object:Author
      name: Zonia Lemke
      biography: ''
  - &8 !ruby/object:Book
    title: The Glory and the Dream
    author: &2 !ruby/object:Author
      name: Mr. Eufemia Kessler
      biography: ''
- - *1
  - *2
- - !ruby/object:Reader
    name: Hot Pie
    email: adrian@bauchdaniel.com
    city: Sar Meel
    street: Howell Parks
    house: 1
  - &9 !ruby/object:Reader
    name: Erreg
    email: andytillman@gutkowski.net
    city: Old Ghis
    street: Marvin Tunnel
    house: 10
- - !ruby/object:Order
    book: &5 !ruby/object:Book
      title: A Time of Gifts
      author: !ruby/object:Author
        name: Graham Dooley
        biography: ''
    reader: &4 !ruby/object:Reader
      name: Rhea Royce
      email: errolbartoletti@wittinghalvorson.biz
      city: Vaes Dothrak
      street: Lang Valley
      house: 9
    date: 2018-11-09 21:41:31.789627853 +02:00
  - !ruby/object:Order
    book: &3 !ruby/object:Book
      title: The Man Within
      author: !ruby/object:Author
        name: Lee Hauck DVM
        biography: ''
    reader: &6 !ruby/object:Reader
      name: Ezzelyno
      email: britney@walkerledner.biz
      city: Sar Meel
      street: Pollich Centers
      house: 10
    date: 2018-11-09 21:41:31.789643441 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-09 21:41:31.789649477 +02:00
  - !ruby/object:Order
    book: *5
    reader: *6
    date: 2018-11-09 21:41:31.789653581 +02:00
  - !ruby/object:Order
    book: &7 !ruby/object:Book
      title: Number the Stars
      author: !ruby/object:Author
        name: Twanna Schaden IV
        biography: ''
    reader: !ruby/object:Reader
      name: Jory Cassel
      email: blaine@boyer.com
      city: Bayasabhad
      street: Purdy Points
      house: 5
    date: 2018-11-09 21:41:31.789658346 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Beyond the Mexique Bay
      author: !ruby/object:Author
        name: Basilia Zemlak
        biography: ''
    reader: *6
    date: 2018-11-09 21:41:31.789663170 +02:00
  - !ruby/object:Order
    book: *5
    reader: !ruby/object:Reader
      name: Balon Swann
      email: harland@donnelly.org
      city: Sar Meel
      street: Pollich Drives
      house: 5
    date: 2018-11-09 21:41:31.789667250 +02:00
  - !ruby/object:Order
    book: *7
    reader: *4
    date: 2018-11-09 21:41:31.789671462 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-09 21:41:31.789675374 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-09 21:41:31.789679202 +02:00
  - !ruby/object:Order
    book: *3
    reader: *4
    date: 2018-11-09 21:41:31.789682982 +02:00
  - !ruby/object:Order
    book: *8
    reader: *9
    date: 2018-11-09 21:41:31.809078837 +02:00
