---
- - !ruby/object:Book
    title: Waiting for the Barbarians
    author: &1 !ruby/object:Author
      name: Tai Nikolaus
      biography: ''
- - *1
- - !ruby/object:Reader
    name: Alyn Frey
    email: darcel@morar.io
    city: Tyrosh
    street: Josphine Street
    house: 8
- - !ruby/object:Order
    book: &4 !ruby/object:Book
      title: Some Buried Caesar
      author: !ruby/object:Author
        name: Yasmine Fadel
        biography: ''
    reader: &3 !ruby/object:Reader
      name: Cleon
      email: jeramybuckridge@schillerlockman.org
      city: Pentos
      street: Herbert Radial
      house: 4
    date: 2018-11-15 19:09:14.591737537 +02:00
  - !ruby/object:Order
    book: &2 !ruby/object:Book
      title: Vanity Fair
      author: !ruby/object:Author
        name: Vickey Bruen
        biography: ''
    reader: &5 !ruby/object:Reader
      name: Deana Hardyng
      email: suebartell@aufderharheathcote.biz
      city: Sar Meel
      street: Blaine Street
      house: 5
    date: 2018-11-15 19:09:14.591749616 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-15 19:09:14.591755313 +02:00
  - !ruby/object:Order
    book: *4
    reader: *5
    date: 2018-11-15 19:09:14.591759391 +02:00
  - !ruby/object:Order
    book: &6 !ruby/object:Book
      title: Ah, Wilderness!
      author: !ruby/object:Author
        name: Donnie Hamill
        biography: ''
    reader: !ruby/object:Reader
      name: Jhaqo
      email: bertflatley@gleasonmetz.io
      city: Qarth
      street: Cruickshank Brook
      house: 2
    date: 2018-11-15 19:09:14.591764081 +02:00
  - !ruby/object:Order
    book: !ruby/object:Book
      title: Eyeless in Gaza
      author: !ruby/object:Author
        name: Yolonda Trantow
        biography: ''
    reader: *5
    date: 2018-11-15 19:09:14.591768183 +02:00
  - !ruby/object:Order
    book: *4
    reader: !ruby/object:Reader
      name: Gormon Tyrell
      email: francoise@mcdermott.info
      city: Bayasabhad
      street: Bashirian Row
      house: 10
    date: 2018-11-15 19:09:14.591772021 +02:00
  - !ruby/object:Order
    book: *6
    reader: *3
    date: 2018-11-15 19:09:14.591776015 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-15 19:09:14.591779889 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-15 19:09:14.591783919 +02:00
  - !ruby/object:Order
    book: *2
    reader: *3
    date: 2018-11-15 19:09:14.591787745 +02:00
